kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers: 
      - name: webapp
        image: nginx
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
